### ISSUE TITLE
Filenames can be too long on Windows

### ISSUE THREAD

**Issue by wch** [r-lib/pak#252]
We are trying to use pak to install dependencies for shiny in GitHub Actions. One of these dependencies is [bslib](https://github.com/rstudio/bslib/), and it fails to build/install with pak. (https://github.com/rstudio/shiny/pull/3230#issuecomment-749857833)

I think the problem is that some filenames are longer than the max length on typical Windows installations.

I think this is the directory where pak tries to unzip the files:

```
C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\Rtmp4K8oTQ\\file10406c64986/src/contrib/bslib_0.2.3.9000_338b05fc5aa551c0cb62dae2ce73ad8c2ceb8403.tar.gz-tree
```

And inside of that, it wants to write the following file:

```
rstudio-bslib-338b05f/inst/lib/bootstrap-accessibility-plugin/plugins/js/bootstrap-accessibility_1.0.3.min.js
```

It fails on that file: https://github.com/rstudio/shiny/runs/1597854296?check_suite_focus=true#step:10:376

The total length of the combined path is 263 characters, which I believe is longer than the max filename length on Windows.

This isn't exactly a bug in pak, but does mean that pak can't be used for GitHub actions on packages that use bslib. The filename in bslib is pretty long, but not crazily long. We could shorten it, but I suspect that other packages would run into the same problem.

**Comment by gaborcsardi** [comment]
As a workaround you can try setting the `TMPDIR` env var to a shorter path.

**Comment by gaborcsardi** [comment]
The unzipping part will be solved by https://github.com/r-lib/zip/issues/63, but there might be other issues when using the unzipped files to do `R CMD build` and then `R CMD INSTALL`. 

Hopefully the final unzip is OK, that is done by `unzip.exe`, so it'll be harder to fix.

**Comment by wch** [comment]
For future reference, here's the change that I made to our workflow to create the temp directory and use it when pak installs the dependencies: [`950afd3` (#3230)](https://github.com/rstudio/shiny/pull/3230/commits/950afd32f1fabee140f77587a3c8d232fd6e88f8)

This is the diff:

```diff
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -79,7 +79,15 @@ jobs:
           brew install cairo
           brew install harfbuzz fribidi
 
+      # Use a shorter temp directory for pak installations, due to filename
+      # length issues on Windows. https://github.com/r-lib/pak/issues/252
+      - name: Windows temp dir
+        if: runner.os == 'Windows'
+        run: New-Item -Path "C:\" -Name "paktmp" -ItemType Directory
+
       - name: Install dependencies
+        env:
+          TMPDIR: "c:\\paktmp"
         run: |
           pak::pkg_install("curl") # install before installing deps
           pak::local_install_dev_deps(upgrade = TRUE)
```

**Comment by jimhester** [comment]
https://github.com/r-lib/zip/issues/63 should be fixed in the devel version of zip I believe.

**Comment by gaborcsardi** [comment]
We can give it a shot then. I am fairly sure that we'll still get (different) errors with pak, because it'll try to `R CMD build` and `R CMD INSTALL` the same path. But I'll give it a try.

**Comment by gaborcsardi** [comment]
Just experimented with #268, and apparently, dev zip still has an issue with long path names. Will work on zip now to solve this.

**Comment by gaborcsardi** [comment]
https://github.com/r-lib/zip/pull/71 seems to fix the unzip issue. But then there are other issues, with `R CMD build`:

```
x Failed to create source package thematic 0.1.1.9000 (17m 0.5s)
(############ ) | [BLD]  34/35 - 1 | [INS]  34/35     | building thematic
Error: Failed to create source package 'thematic' from source tree 'C:\\Users\\csard\\AppData\\Local\\Temp\\RtmpOIwDlH\\file5a64747d3a96/src/contrib/thematic_0.1.1.9000_03b8c7b8e762a3a21c6aacbe71ea183433240182.tar.gz-tree', stdout + stderr (last 10 lines):

OE> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
OE>   problem copying .\rstudio-thematic-03b8c7b\tests\testthat\auto_theme_shiny\with_theme\tests\shinytest\mytest-expected-mac\001.json to C:\Users\csard\AppData\Local\Temp\Rtmpk3TsBP\Rbuild721016831e56\rstudio-thematic-03b8c7b\tests\testthat\auto_theme_shiny\with_theme\tests\shinytest\mytest-expected-mac\001.json: No such file or directory
OE> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
OE>   problem copying .\rstudio-thematic-03b8c7b\tests\testthat\auto_theme_shiny\with_theme\tests\shinytest\mytest-expected-mac\001.png to C:\Users\csard\AppData\Local\Temp\Rtmpk3TsBP\Rbuild721016831e56\rstudio-thematic-03b8c7b\tests\testthat\auto_theme_shiny\with_theme\tests\shinytest\mytest-expected-mac\001.png: No such file or directory
OE> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
OE>   problem copying .\rstudio-thematic-03b8c7b\tests\testthat\auto_theme_shiny\with_theme\tests\shinytest\mytest-expected-win\001.json to C:\Users\csard\AppData\Local\Temp\Rtmpk3TsBP\Rbuild721016831e56\rstudio-thematic-03b8c7b\tests\testthat\auto_theme_shiny\with_theme\tests\shinytest\mytest-expected-win\001.json: No such file or directory
OE> Warning in file.copy(pkgname, Tdir, recursive = TRUE, copy.date = TRUE) :
OE>   problem copying .\rstudio-thematic-03b8c7b\tests\testthat\auto_theme_shiny\with_theme\tests\shinytest\mytest-expected-win\001.png to C:\Users\csard\AppData\Local\Temp\Rtmpk3TsBP\Rbuild721016831e56\rstudio-thematic-03b8c7b\tests\testthat\auto_theme_shiny\with_theme\tests\shinytest\mytest-expected-win\001.png: No such file or directory
OE>  ERROR
OE> copying to build directory failed
```

**Comment by gaborcsardi** [comment]
While some workarounds are possible, e.g. mapping the directory to a drive, or using a symlink, it does not seem that we can reliable fix `R CMD build`, especially on older Windows versions.

What we can do is
- [ ] use shorter paths, so at least less packages fail
- [ ] have a better error message for the failures

**Comment by gaborcsardi** [comment]
Actually, I'll try to work around it using a junction.

**Comment by gaborcsardi** [comment]
We can't use junctions, because pkgbuild calls `normalizePath()` on the package path, and that resolves the junction back to the long file name. 

But https://github.com/r-lib/pkgdepends/pull/236 implements a much shorter path, anyway, so we don't actually need junctions. We'll also give a nice warning for long paths once that PR is merged.
