### ISSUE TITLE
Cannot download from behind proxy

### ISSUE THREAD

**Issue by Luke-Symes-Tsy** [r-lib/pak#735]
My Windows computer, with R 4.4.2, uses a proxy to access the internet.

Using `options(download.file.method = "wininet")`, I can successfully run `install.packages("zip")`. However, running `pak::pkg_install("zip")` fails with:

```
Error: 
! error in pak subprocess
Caused by error in `download.file(url, tmp, quiet = TRUE)`:
! cannot open URL 'http://bioconductor.org/config.yaml'
```

For example:
![image](https://github.com/user-attachments/assets/4403e3d9-ad76-40f0-bc42-285ea22a34ea)

It seems like pak is not recognising the download.file.method option?

**Comment by gaborcsardi** [comment]
pak does not use `download.file()` and does not use `download.file.method`. This is a bug that is possibly fixed in the devel version, you can install it like this:
https://pak.r-lib.org/reference/install.html#nightly-builds

**Comment by Luke-Symes-Tsy** [comment]
I tracked down the issue to `pkgcache` trying to update the Bioconductor metadata. `pkgcache` essentially calls `pkgcache:::bioconductor$.internal$read_url("http://bioconductor.org/config.yaml")` which uses `download.file`.

However, the issue seems to be that `pak` does not tell `callr` (which runs `pkgcache` etc) to use the user's `.Rprofile` - it defaults to `user = "project"` which looks for a project-specific `.Rprofile`: https://github.com/r-lib/pak/blob/683f1be2cc2662d8e4073167910a1dd2f1e63b89/R/subprocess.R#L143

If I create a project-specific `.Rprofile` with the right options, then `pak::pkg_install("zip")` works (after a session restart):
```
Sys.setenv(ALL_PROXY = ":@<proxy_url>:<proxy_port>")
options(download.file.method = "curl")
```

What I think should be happening, is if a project-specific `.Rprofile` does not exist, we should default to `user = TRUE` which tells `callr` to use `R_PROFILE_USER` or `~/.Rprofile` if it exists:
```
user_profile = if (Sys.getenv("RENV_PROJECT") != "") FALSE else if (file.exists(".Rprofile")) "project"  else TRUE
```

Note: I tested the latest devel version of `pak` and avoided the Bioconductor error (since Bioconductor is now turned off by default); however my `ALL_PROXY` setting was still not being picked up from my user `~/.Rprofile`, but was from a project-specific `.Rprofile`.

**Comment by jonbry** [comment]
I'm running into the same issue and may be caused by the firewall on a corporate network. When I looked into it further, there's a certificate issue similar to the one found [here]. (https://forum.posit.co/t/rstudio-cant-access-package-manager-url-but-i-can-with-a-browser/197192/3). Is this something that is potentially being accounted for in the future or do I need to work with our team to adjust firewall settings? If so, are there any other non-Posit/RStudio domains I should be aware of for `pak`?

Currently using:
- R 4.5.3
- pak 0.9.5

**Comment by gaborcsardi** [comment]
I believe this is already fixed in the dev version of pak, you can try it if you like this: https://pak.r-lib.org/reference/install.html#nightly-builds

**Comment by jonbry** [comment]
> I believe this is already fixed in the dev version of `pak`, you can try it if you like this: https://pak.r-lib.org/reference/install.html#nightly-builds

When I ran the linked code, it downloads `pak v0.9.4.9000`, and I still get the same error. Is this the right version? I originally found this error with `devtools::build_readme`, which looks to have a `pak v0.9.5` [dependency](https://github.com/r-lib/devtools/blob/5a10248bb3b727f84a34e517b92fff118652be1e/DESCRIPTION#L28). With the dev version, I still get the error with `build_readme` as well as any other package I try to install with `pak::pak()`

**Comment by gaborcsardi** [comment]
@jonbry Ooops, sorry, try again!

**Comment by jonbry** [comment]
> [@jonbry](https://github.com/jonbry) Ooops, sorry, try again!

The nightly link downloaded `pak v0.9.5.9000` and is now works perfectly! Thanks for your help!

**Comment by jonbry** [comment]
I ran into the Bioconductor issue with redeploying an app using `rsconnect` (during the Capturing R dependencies portion):
```
Error: invalid version specification ‘unknown version: Bioconductor version cannot be validated; no internet connection?
    See #troubleshooting section in vignette’
```
Could this be connected to the `pak` issue? This is happening on my work computer, which has `pak 0.10.0` and it looks like the dev version was upgraded to `0.10.9000`.

**Comment by gaborcsardi** [comment]
@jonbry I don't think that message is coming from pak. Seems like it is coming from BiocManager: https://github.com/Bioconductor/BiocManager/blob/1ab94defab51a21f7de7594e71a30288b2577ad6/R/version.R#L8

**Comment by gaborcsardi** [comment]
I think this is already fixed in dev pak, to be released soon, so I am going to close this.
