### ISSUE TITLE
Metadata Failure Kills Everything

### ISSUE THREAD

**Issue by slopp** [r-lib/pak#96]
```
pak::pkg_install('ISLR')
ℹ Checking for package metadata updates
✖ Metadata download failed                              
Error: Failed to connect to localhost port 80: Connection refused
```

```
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 os       macOS  10.14.2              
 system   x86_64, darwin13.4.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       <NA>                        
 date     2019-03-05                  

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 ! package      * version    date       lib source                               
   assertthat     0.2.0      2017-04-11 [1] CRAN (R 3.3.2)                       
   backports      1.1.3      2018-12-14 [1] RSPM (R 3.3.3)                       
   bindr          0.1.1      2018-03-13 [1] RSPM (R 3.3.3)                       
   bindrcpp       0.2.2      2018-03-29 [1] RSPM (R 3.3.3)                       
   brew           1.0-6      2011-04-13 [1] CRAN (R 3.3.0)                       
   callr          3.1.1.9000 2019-03-05 [1] Github (r-lib/callr@46734c1)         
   cli            1.0.1.9000 2019-01-23 [1] Github (r-lib/cli@94e2fc5)           
   cliapp         0.1.0.9000 2019-01-03 [1] Github (r-lib/cliapp@35b184a)        
   colorspace     1.3-2      2016-12-14 [1] CRAN (R 3.3.2)                       
   crayon         1.3.4      2017-09-16 [1] CRAN (R 3.3.2)                       
   curl           3.3        2019-01-10 [1] RSPM (R 3.3.3)                       
   data.table     1.10.4     2017-02-01 [1] CRAN (R 3.3.2)                       
   debugme        1.1.0.9000 2018-05-05 [1] Github (gaborcsardi/debugme@f4a116a) 
   desc           1.2.0      2019-03-05 [1] Github (r-lib/desc@ef9e3a4)          
   devtools       2.0.1      2018-10-26 [1] RSPM (R 3.3.3)                       
   DiagrammeR   * 1.0.0      2018-03-01 [1] RSPM (R 3.3.3)                       
   digest         0.6.18     2018-10-10 [1] RSPM (R 3.3.3)                       
   distill      * 0.6.0.9000 2019-03-05 [1] Github (rstudio/distill@6aaffa3)     
   downloader     0.4        2015-07-09 [1] RSPM (R 3.3.3)                       
   dplyr          0.7.7      2018-10-16 [1] RSPM (R 3.3.3)                       
 V evaluate       0.10.1     2019-02-12 [1] RSPM (R 3.3.3)                       
   fansi          0.4.0      2018-10-05 [1] RSPM (R 3.3.3)                       
   filelock       1.0.2.9000 2019-01-03 [1] Github (r-lib/filelock@060bd83)      
   formatR        1.5        2017-04-25 [1] RSPM (R 3.3.3)                       
   fs             1.2.2      2018-03-21 [1] RSPM (R 3.3.3)                       
   ggplot2      * 3.0.0.9000 2018-10-19 [1] Github (tidyverse/ggplot2@3550772)   
   glue           1.3.0.9000 2019-02-25 [1] Github (tidyverse/glue@8188cea)      
   gridExtra      2.3        2017-09-09 [1] CRAN (R 3.3.2)                       
   gtable         0.2.0      2016-02-26 [1] CRAN (R 3.3.0)                       
   hms            0.4.2      2018-03-10 [1] RSPM (R 3.3.3)                       
   htmltools      0.3.6      2017-04-28 [1] CRAN (R 3.3.2)                       
   htmlwidgets    1.2.1      2018-10-19 [1] Github (ramnathv/htmlwidgets@29ca4f7)
   httr           1.3.1      2017-08-20 [1] CRAN (R 3.3.2)                       
   igraph         1.1.2      2017-07-21 [1] CRAN (R 3.3.2)                       
   influenceR     0.1.0      2015-09-03 [1] RSPM (R 3.3.3)                       
   jsonlite       1.6        2018-12-07 [1] RSPM (R 3.3.3)                       
 V knitr          1.20       2018-12-10 [1] RSPM (R 3.3.3)                       
   lazyeval       0.2.1      2017-10-29 [1] CRAN (R 3.3.2)                       
   magrittr       1.5        2014-11-22 [1] CRAN (R 3.3.0)                       
   memoise        1.1.0      2017-04-21 [1] CRAN (R 3.3.2)                       
   munsell        0.4.3      2016-02-13 [1] CRAN (R 3.3.0)                       
   packrat        0.4.8-52   2017-11-16 [1] Github (rstudio/packrat@4b3e402)     
   pak            0.1.2.9000 2019-03-05 [1] Github (r-lib/pak@2a83117)           
   pillar         1.3.1      2018-12-15 [1] RSPM (R 3.3.3)                       
   pkgbuild       1.0.2.9000 2019-01-03 [1] Github (r-lib/pkgbuild@6e4ebdf)      
   pkgcache       1.0.3.9000 2019-03-05 [1] Github (r-lib/pkgcache@0c63a85)      
   pkgconfig      2.0.2      2018-08-16 [1] RSPM (R 3.3.3)                       
   pkgload        1.0.1.9000 2019-01-03 [1] Github (r-lib/pkgload@0ef4f58)       
   plotly         4.7.1      2017-07-29 [1] CRAN (R 3.3.2)                       
   plyr           1.8.4      2016-06-08 [1] CRAN (R 3.3.0)                       
   prettyunits    1.0.2      2015-07-13 [1] RSPM (R 3.3.3)                       
 V processx       3.2.1      2019-03-05 [1] Github (r-lib/processx@823819d)      
   progress       1.2.0.9000 2019-02-25 [1] Github (r-lib/progress@2ba1a03)      
   ps             1.3.0      2018-12-21 [1] RSPM (R 3.3.3)                       
   purrr          0.2.4      2017-10-18 [1] CRAN (R 3.3.2)                       
   R6             2.4.0      2019-02-14 [1] RSPM (R 3.3.3)                       
   radix          0.5        2018-09-17 [1] CRAN (R 3.3.3)                       
   rappdirs       0.3.1      2016-03-28 [1] CRAN (R 3.3.0)                       
   RColorBrewer   1.1-2      2014-12-07 [1] CRAN (R 3.3.0)                       
   Rcpp           1.0.0.3    2019-03-05 [1] Github (RcppCore/Rcpp@08344ae)       
   readr          1.1.1      2017-05-16 [1] CRAN (R 3.3.2)                       
   rematch2       2.0.0.9000 2019-01-03 [1] Github (MangoTheCat/rematch2@180fb61)
   remotes        2.0.0      2018-10-11 [1] RSPM (R 3.3.3)                       
   reprex         0.1.2      2018-01-26 [1] CRAN (R 3.3.3)                       
   rgexf          0.15.3     2015-03-24 [1] RSPM (R 3.3.3)                       
   rlang          0.3.1.9000 2019-02-25 [1] Github (r-lib/rlang@7243c6d)         
   rmarkdown      1.11       2018-12-08 [1] RSPM (R 3.3.3)                       
   Rook           1.1-1      2014-10-20 [1] RSPM (R 3.3.3)                       
   rprojroot      1.3-2      2018-01-03 [1] CRAN (R 3.3.2)                       
   rsconnect      0.8.10     2018-10-23 [1] Github (rstudio/rsconnect@e6a7248)   
 V rstudioapi     0.8.0.9003 2019-03-05 [1] Github (rstudio/rstudioapi@f4418fc)  
   scales         0.5.0      2017-08-24 [1] CRAN (R 3.3.2)                       
   selectr        0.4-1      2018-04-06 [1] RSPM (R 3.3.3)                       
   sessioninfo    1.1.1      2018-11-05 [1] RSPM (R 3.3.3)                       
   stringi        1.3.1      2019-02-13 [1] RSPM (R 3.3.3)                       
   stringr        1.4.0      2019-02-10 [1] RSPM (R 3.3.3)                       
   testthat       2.0.0      2017-12-13 [1] CRAN (R 3.3.2)                       
   tibble       * 2.0.1      2019-01-12 [1] RSPM (R 3.3.3)                       
   tidyr          0.8.0      2018-01-29 [1] CRAN (R 3.3.3)                       
   tidyselect     0.2.3      2017-11-06 [1] CRAN (R 3.3.2)                       
   usethis        1.4.0.9000 2019-02-11 [1] Github (r-lib/usethis@8e3c151)       
   uuid           0.1-2      2015-07-28 [1] CRAN (R 3.3.0)                       
   viridis        0.5.1      2018-03-29 [1] RSPM (R 3.3.3)                       
   viridisLite    0.3.0      2018-02-01 [1] RSPM (R 3.3.3)                       
   visNetwork     2.0.4      2018-06-14 [1] RSPM (R 3.3.3)                       
   whisker        0.3-2      2013-04-28 [1] RSPM (R 3.3.3)                       
   withr          2.1.2.9000 2019-01-03 [1] Github (r-lib/withr@be57595)         
   XML            3.98-1.9   2017-06-19 [1] CRAN (R 3.3.2)                       
   xml2           1.2.0      2018-01-24 [1] RSPM (R 3.3.3)                       
   yaml           2.2.0      2018-07-25 [1] RSPM (R 3.3.3)                       
```

**Comment by gaborcsardi** [comment]
I believe that this was fixed in https://github.com/r-lib/pkgcache/commit/c147518e3c5136672b0cded291d5d8ed3382a8cc

You probably need to rerun `pak_setup()` and then reload pak. You can check the version in the pak library with `pak::pkg_status("pkgcache", lib = pak:::get_private_lib())`

**Comment by slopp** [comment]
This did not fix the issue:

In a new R session I ran:

```
pak::pak_setup()
```

Restarted R again, then ran:

```
library(pak)
```

The output of `pak::pkg_status("pkgcache", lib = pak:::get_private_lib())` shows the correct sha:

0c63a85f3b393182bfe6d8cd7c7d7c56da859296

Same error report

**Comment by gaborcsardi** [comment]
So why is it trying to connect to localhost? Is that some proxy?

**Comment by slopp** [comment]
ok, so I was able to run successfully in a terminal, the issue appears to be isolated to RStudio. 

I am running: 1.2.872  on Mac MoJave

**Comment by slopp** [comment]
It does work on RStudio  Server 1.2.11 running on Linux ... so perhaps my RStudio install is just borked. I'll close this out for now, thanks for the help!
